// ...existing code...
use Symfony\Component\HttpKernel\Exception\HttpException;
// ...existing code...

public function render($request, Exception $exception)
{
    // ...existing code...
    if ($exception instanceof HttpException && $exception->getStatusCode() == 403) {
        return response()->view('errors.403', [], 403);
    }
    // ...existing code...
}
